import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Dict, List
import logging

logger = logging.getLogger(__name__)


class EmailReporter:
    """Sends a single comprehensive extraction report via SMTP after all candidates are processed."""

    def __init__(self, config: Dict):
        self.smtp_server = config.get("SMTP_SERVER")
        self.smtp_port = int(config.get("SMTP_PORT", 587))
        self.smtp_username = config.get("SMTP_USERNAME")
        self.smtp_password = config.get("SMTP_PASSWORD")
        self.from_email = config.get("REPORT_FROM_EMAIL")
        self.to_email = config.get("REPORT_TO_EMAIL")

        if not all([self.smtp_server, self.smtp_username, self.smtp_password, self.from_email, self.to_email]):
            logger.warning("Email reporting configuration is incomplete. Email reports will be disabled.")
            self.enabled = False
        else:
            self.enabled = True

    def send_report(self, report: Dict):
        """
        Sends a single comprehensive report email after all candidates are processed.

        Args:
            report: The full report dict generated by _generate_json_report() in service.py.
                    Expected keys: run_metadata, summary, candidates, failed_candidate_details
        """
        if not self.enabled:
            logger.info("Email reporting is disabled. Skipping report email.")
            return

        try:
            run_metadata = report.get("run_metadata", {})
            summary = report.get("summary", {})
            candidates = report.get("candidates", [])
            failed_details = report.get("failed_candidate_details", [])

            # Build subject
            run_date = run_metadata.get("finished_at", datetime.now().isoformat())
            try:
                run_date_fmt = datetime.fromisoformat(run_date).strftime("%B %d, %Y at %I:%M %p")
            except Exception:
                run_date_fmt = run_date

            subject = f"[WBL] Email Extraction Report — {run_date_fmt}"

            body = self._generate_html_body(run_metadata, summary, candidates, failed_details, run_date_fmt)

            msg = MIMEMultipart("alternative")
            msg["From"] = self.from_email
            msg["To"] = self.to_email
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "html"))

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.ehlo()
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                server.send_message(msg)

            logger.info("Extraction report sent to %s", self.to_email)

        except Exception as e:
            logger.error("Failed to send extraction report email: %s", e)

    def _generate_html_body(
        self,
        run_metadata: Dict,
        summary: Dict,
        candidates: List[Dict],
        failed_details: List[Dict],
        run_date_fmt: str,
    ) -> str:

        # ── Duration ──────────────────────────────────────────────────────────
        duration_seconds = run_metadata.get("duration_seconds")
        if duration_seconds is not None:
            hours = int(duration_seconds // 3600)
            minutes = int((duration_seconds % 3600) // 60)
            duration_str = f"{hours}h {minutes}m"
        else:
            duration_str = "N/A"

        started_at = run_metadata.get("started_at", "N/A")
        try:
            started_at = datetime.fromisoformat(started_at).strftime("%B %d, %Y at %I:%M %p")
        except Exception:
            pass

        # ── Summary numbers ───────────────────────────────────────────────────
        total = summary.get("total_candidates", 0)
        success = summary.get("successful_candidates", 0)
        failed = summary.get("failed_candidates", 0)
        contacts_inserted = summary.get("vendor_contacts_inserted", 0)
        positions_inserted = summary.get("positions_inserted", 0)
        total_found = summary.get("total_found_valid", 0)
        total_passed_filters = summary.get("total_passed_filters", 0)
        fetched = summary.get("total_emails_fetched", 0)
        duplicates = summary.get("total_duplicates", 0)
        non_vendor = summary.get("total_non_vendor", 0)

        success_rate = f"{round(success / total * 100)}%" if total else "0%"

        # ── Extracted contacts rows ───────────────────────────────────────────
        all_found = run_metadata.get("all_found_contacts", [])
        extracted_rows_html = ""
        if all_found:
            for c in all_found[:50]:  # Limit to 50 for the email report
                name = c.get("name") or "—"
                c_email = c.get("email") or "—"
                company_name = c.get("company") or "—"
                extracted_rows_html += f"""
                <tr>
                    <td style="padding:10px 12px; border-bottom:1px solid #f3f4f6;">{name}</td>
                    <td style="padding:10px 12px; border-bottom:1px solid #f3f4f6; color:#6b7280;">{c_email}</td>
                    <td style="padding:10px 12px; border-bottom:1px solid #f3f4f6; color:#6b7280;">{company_name}</td>
                </tr>"""

        # ── Failed candidates rows ─────────────────────────────────────────────
        failed_rows_html = ""
        if failed_details:
            for c in failed_details:
                error_msg = c.get("error") or "No specific error recorded"
                name = c.get("candidate_name") or "—"
                email = c.get("candidate_email") or "—"
                failed_rows_html += f"""
                <tr>
                    <td style="padding:10px 12px; border-bottom:1px solid #fee2e2;">{name}</td>
                    <td style="padding:10px 12px; border-bottom:1px solid #fee2e2; color:#6b7280;">{email}</td>
                    <td style="padding:10px 12px; border-bottom:1px solid #fee2e2; color:#dc2626;">{error_msg}</td>
                </tr>"""
        else:
            failed_rows_html = """
                <tr>
                    <td colspan="3" style="padding:12px; text-align:center; color:#6b7280;">
                        No failed candidates 🎉
                    </td>
                </tr>"""

        # ── Pre-compute extracted contacts section ─────────────────────────────
        extracted_section = ""
        if extracted_rows_html:
            more_info = "(Showing up to 50 contacts. Full list available in JSON report.)" if len(all_found) > 50 else ""
            extracted_section = f"""
            <h2 style="font-size:16px; font-weight:600; color:#111827; margin:28px 0 12px;">Recently Discovered Contacts</h2>
            <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse; border:1px solid #e5e7eb; border-radius:8px; overflow:hidden;">
                <thead>
                    <tr style="background:#f9fafb;">
                        <th style="padding:10px 12px; text-align:left; font-size:12px; color:#6b7280; text-transform:uppercase; letter-spacing:0.05em; border-bottom:1px solid #e5e7eb;">Name</th>
                        <th style="padding:10px 12px; text-align:left; font-size:12px; color:#6b7280; text-transform:uppercase; letter-spacing:0.05em; border-bottom:1px solid #e5e7eb;">Email</th>
                        <th style="padding:10px 12px; text-align:left; font-size:12px; color:#6b7280; text-transform:uppercase; letter-spacing:0.05em; border-bottom:1px solid #e5e7eb;">Company</th>
                    </tr>
                </thead>
                <tbody>
                    {extracted_rows_html}
                </tbody>
            </table>
            <p style="margin:12px 0 0; font-size:12px; color:#6b7280;">{more_info}</p>
            """

        failed_section = f"""
        <h2 style="font-size:16px; font-weight:600; color:#dc2626; margin:32px 0 12px;">
            ❌ Failed Candidates ({failed})
        </h2>
        <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse; background:#fff5f5; border:1px solid #fecaca; border-radius:8px; overflow:hidden;">
            <thead>
                <tr style="background:#fee2e2;">
                    <th style="padding:10px 12px; text-align:left; font-size:12px; color:#991b1b; text-transform:uppercase; letter-spacing:0.05em;">Name</th>
                    <th style="padding:10px 12px; text-align:left; font-size:12px; color:#991b1b; text-transform:uppercase; letter-spacing:0.05em;">Email</th>
                    <th style="padding:10px 12px; text-align:left; font-size:12px; color:#991b1b; text-transform:uppercase; letter-spacing:0.05em;">Error / Cause</th>
                </tr>
            </thead>
            <tbody>
                {failed_rows_html}
            </tbody>
        </table>
        """ if failed > 0 else ""

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Extraction Report</title>
</head>
<body style="margin:0; padding:0; background:#f3f4f6; font-family:Arial, Helvetica, sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6; padding:32px 0;">
<tr><td align="center">
<table width="640" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 4px 20px rgba(0,0,0,0.08);">

    <!-- HEADER -->
    <tr>
        <td style="background:linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%); padding:32px 40px;">
            <p style="margin:0 0 4px; font-size:12px; color:#93c5fd; text-transform:uppercase; letter-spacing:0.1em;">Whitebox Learning</p>
            <h1 style="margin:0 0 8px; font-size:24px; font-weight:700; color:#ffffff;">Email Extraction Report</h1>
            <p style="margin:0; font-size:14px; color:#bfdbfe;">Run completed on {run_date_fmt}</p>
        </td>
    </tr>

    <!-- BODY -->
    <tr>
        <td style="padding:32px 40px;">

            <!-- Run info -->
            <p style="margin:0 0 24px; font-size:14px; color:#6b7280; line-height:1.6;">
                This report summarises the email extraction run that processed all active candidates.
                The run started at <strong>{started_at}</strong> and completed in <strong>{duration_str}</strong>.
            </p>

            <!-- Summary stats cards -->
            <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
                <tr>
                    <td width="16.6%" style="padding:0 4px 0 0;">
                        <div style="background:#eff6ff; border-radius:8px; padding:16px; text-align:center;">
                            <p style="margin:0 0 4px; font-size:22px; font-weight:700; color:#1d4ed8;">{total}</p>
                            <p style="margin:0; font-size:9px; color:#3b82f6; text-transform:uppercase; letter-spacing:0.05em;">Candidates</p>
                        </div>
                    </td>
                    <td width="16.6%" style="padding:0 4px;">
                        <div style="background:#f0fdf4; border-radius:8px; padding:16px; text-align:center;">
                            <p style="margin:0 0 4px; font-size:22px; font-weight:700; color:#15803d;">{success}</p>
                            <p style="margin:0; font-size:9px; color:#16a34a; text-transform:uppercase; letter-spacing:0.05em;">Success</p>
                        </div>
                    </td>
                    <td width="16.6%" style="padding:0 4px;">
                        <div style="background:#fff5f5; border-radius:8px; padding:16px; text-align:center;">
                            <p style="margin:0 0 4px; font-size:22px; font-weight:700; color:#dc2626;">{failed}</p>
                            <p style="margin:0; font-size:9px; color:#ef4444; text-transform:uppercase; letter-spacing:0.05em;">Failed</p>
                        </div>
                    </td>
                    <td width="16.6%" style="padding:0 4px;">
                        <div style="background:#f0fdfa; border-radius:8px; padding:16px; text-align:center;">
                            <p style="margin:0 0 4px; font-size:22px; font-weight:700; color:#0d9488;">{total_passed_filters}</p>
                            <p style="margin:0; font-size:9px; color:#14b8a6; text-transform:uppercase; letter-spacing:0.05em;">Extracted</p>
                        </div>
                    </td>
                    <td width="16.6%" style="padding:0 4px;">
                        <div style="background:#fefce8; border-radius:8px; padding:16px; text-align:center;">
                            <p style="margin:0 0 4px; font-size:22px; font-weight:700; color:#ca8a04;">{contacts_inserted}</p>
                            <p style="margin:0; font-size:9px; color:#eab308; text-transform:uppercase; letter-spacing:0.05em;">Inserted (New)</p>
                        </div>
                    </td>
                </tr>
            </table>

            <!-- Detailed summary table -->
            <h2 style="font-size:16px; font-weight:600; color:#111827; margin:0 0 12px;">📊 Run Overview</h2>
            <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse; border:1px solid #e5e7eb; border-radius:8px; overflow:hidden; margin-bottom:28px;">
                <thead>
                    <tr style="background:#f9fafb;">
                        <th style="padding:10px 16px; text-align:left; font-size:12px; color:#6b7280; text-transform:uppercase; letter-spacing:0.05em; border-bottom:1px solid #e5e7eb;">Metric</th>
                        <th style="padding:10px 16px; text-align:right; font-size:12px; color:#6b7280; text-transform:uppercase; letter-spacing:0.05em; border-bottom:1px solid #e5e7eb;">Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; color:#374151;">Total Candidates Processed</td>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; font-weight:600; color:#111827; text-align:right;">{total}</td>
                    </tr>
                    <tr style="background:#f9fafb;">
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; color:#374151;">Successful Candidates</td>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; font-weight:600; color:#15803d; text-align:right;">{success}</td>
                    </tr>
                    <tr>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; color:#374151;">Failed Candidates</td>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; font-weight:600; color:#dc2626; text-align:right;">{failed}</td>
                    </tr>
                    <tr style="background:#f9fafb;">
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; color:#374151;">Contacts Extracted (Passed Filters)</td>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; font-weight:600; color:#0d9488; text-align:right;">{total_passed_filters}</td>
                    </tr>
                    <tr style="background:#f9fafb;">
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; color:#374151;">Contacts Inserted (New to DB)</td>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; font-weight:600; color:#ca8a04; text-align:right;">{contacts_inserted}</td>
                    </tr>
                    <tr style="background:#f9fafb;">
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; color:#374151;">Success Rate</td>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; font-weight:600; color:#2563eb; text-align:right;">{success_rate}</td>
                    </tr>
                    <tr>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; color:#374151;">Total Emails Fetched</td>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; font-weight:600; color:#111827; text-align:right;">{fetched:,}</td>
                    </tr>
                    <tr style="background:#f9fafb;">
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; color:#374151;">Duplicates Skipped</td>
                        <td style="padding:12px 16px; border-bottom:1px solid #f3f4f6; font-size:14px; font-weight:600; color:#6b7280; text-align:right;">{duplicates:,}</td>
                    </tr>
                    <tr>
                        <td style="padding:12px 16px; font-size:14px; color:#374151;">Non-Vendor Filtered</td>
                        <td style="padding:12px 16px; font-size:14px; font-weight:600; color:#6b7280; text-align:right;">{non_vendor:,}</td>
                    </tr>
                </tbody>
            </table>

            <!-- Failed candidates section -->
            {failed_section}

            <!-- Extracted Contacts section -->
            {extracted_section}

        </td>
    </tr>

    <!-- FOOTER -->
    <tr>
        <td style="background:#f9fafb; padding:20px 40px; border-top:1px solid #e5e7eb;">
            <p style="margin:0; font-size:12px; color:#9ca3af; text-align:center;">
                This is an automated report generated by the WBL Email Extraction System.<br>
                Run ID: {run_metadata.get("run_id", "N/A")}
            </p>
        </td>
    </tr>

</table>
</td></tr>
</table>

</body>
</html>"""
        return html
